### ISSUE TITLE
Add pre-commit hook with linting and formatting

### ISSUE THREAD

**Issue by wizche** [cyber-defence-campus/mole#81]
Using `ruff` and `pre-commit` packages. Add the following hook configuration at the repo root named `.pre-commit-config.yaml`.
Updated README and add instructions on how to install it (`pre-commit install`)
```
repos:
  - repo: local
    hooks:
      - id: check-code-issues
        name: Check Code Issues
        entry: ruff check
        args: [ -q ]
        language: python
        files: .*\.py$
  - repo: local
    hooks:
      - id: format
        name: Format Code
        entry: ruff format
        language: python
        files: .*\.py$
```
